#!/usr/bin/env -S python3 -u

import argparse, socket, time, json, select, struct, sys, math

DATA_SIZE = 1375

class Sender:
    def __init__(self, host, port):
        self.host = host
        self.port = int(port)
        self.log("Sender starting up using port %s" % self.port)
        self.socket = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        self.socket.bind(('0.0.0.0', 0))

        self.packetsAwaitingResponse = []

        # Window Size, Slow Start Threshold, and the congestion window variables
        self.windowSize = 1
        self.ssthresh = 16
        self.cwnd = 1  

        # the round trip time of a single packet/ack
        self.rtt = 1.0

        self.remote_host = None
        self.remote_port = None

    def log(self, message):
        sys.stderr.write(message + "\n")
        sys.stderr.flush()

    def send(self, message):
        self.log("Sending message '%s'" % json.dumps(message))
        self.socket.sendto(json.dumps(message).encode("utf-8"), (self.host, self.port))

    def recv(self, socket):
        data, addr = socket.recvfrom(65535)

        # Grab the remote host/port if we don't already have it
        if self.remote_host is None:
            self.remote_host = addr[0]
            self.remote_port = addr[1]

        # Make sure we're talking to the same remote host
        if addr != (self.remote_host, self.remote_port):
            self.log("Error:  Received response from unexpected remote; ignoring")
            return None
        else:
            self.log("Received message %s" % data)
            return json.loads(data.decode("utf-8"))

    def run(self):
        seq = 0
        while True:
            # first check if there are any packets living beyond the ttl with no ack
            self.resendLostPackets()
            # send data if possible
            if not (len(self.packetsAwaitingResponse) >= self.windowSize):
                socks = select.select([sys.stdin], [], [], 0.1)[0]
                for conn in socks:
                    data = sys.stdin.read(DATA_SIZE)
                    if len(data) == 0:
                        if len(self.packetsAwaitingResponse) == 0:
                            self.log("All done!")
                            sys.exit(0)
                        else:
                            continue # keep looping until there are no outstanding messages awaiting ack

                    msg = { "type": "msg", "data": data, "seq": seq}
                    self.send(msg)
                    self.packetsAwaitingResponse.append((msg,time.time()))
                    seq += 1

            # Check for incoming ACKs
            socks = select.select([self.socket], [], [], 0.1)[0]
            for conn in socks:
                data = self.recv(conn)

                if data:
                    # Handle ACKs
                    if data["type"] == "ack":
                        ack_seq = data["seq"]
                        ack_time = time.time()
                        self.log(f"Received ACK for packet {ack_seq}")
                        found = False
                        # Update congestion control parameters
                        for packet in self.packetsAwaitingResponse:
                            if packet[0]['seq'] == ack_seq:
                                found = True
                                print("OLD RTT: " + str(self.rtt))
                                # averages out the old rtt with the rtt of the incoming ack-ed packet
                                self.rtt = ((ack_time - packet[1]) + self.rtt) / 2
                                print(" NEW RTT: " + str(self.rtt))
                                if self.cwnd < self.ssthresh:
                                    # Slow start phase (exponential growth)
                                    self.cwnd += 1
                                else:
                                    # Congestion avoidance phase (linear growth)
                                    self.cwnd += 1 / self.cwnd

                                self.windowSize = int(self.cwnd)
                                self.packetsAwaitingResponse.remove(packet)
                                break
                        if not found:
                            print("DUPLICATE ACK WITH SEQ: " + str(ack_seq))
    
        return
    
    def resendLostPackets(self):
        for packet in self.packetsAwaitingResponse:
            if time.time() - packet[1] > (self.rtt * 2):
                y = list(packet)
                y[1] = time.time()
                packet = y
                self.send(packet[0])
                print("Resending message with seq:" + str(packet[0]['seq']))
        return

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='send data')
    parser.add_argument('host', type=str, help="Remote host to connect to")
    parser.add_argument('port', type=int, help="UDP port number to connect to")
    args = parser.parse_args()
    sender = Sender(args.host, args.port)
    sender.run()
