#!/usr/bin/env -S python3 -u

import argparse, socket, time, json, select, struct, sys, math

class Receiver:
    def __init__(self):
        self.socket = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        self.socket.bind(('0.0.0.0', 0))
        self.port = self.socket.getsockname()[1]
        self.log("Bound to port %d" % self.port)

        self.remote_host = None
        self.remote_port = None

        self.recievedSequenceNums = []
        self.recievedData = []

        self.buffer = {}
        self.next_expected_seq = 0 

    def send(self, message):
        self.log("Sent message %s" % json.dumps(message))
        self.socket.sendto(json.dumps(message).encode("utf-8"), (self.remote_host, self.remote_port))

    def recv(self, socket):
        data, addr = socket.recvfrom(65535)

        # Grab the remote host/port if we don't already have it
        if self.remote_host is None:
            self.remote_host = addr[0]
            self.remote_port = addr[1]

        # Make sure we're talking to the same remote host
        if addr != (self.remote_host, self.remote_port):
            self.log("Error:  Received response from unexpected remote; ignoring")
            return None
        else:
            self.log("Received message %s" % data.decode("utf-8"))
            return json.loads(data.decode("utf-8"))

    def log(self, message):
        sys.stderr.write(message + "\n")
        sys.stderr.flush()

    def run(self):
        while True:
            socks = select.select([self.socket], [], [],0.1)[0]
            for conn in socks:
                msg = self.recv(conn)
                self.send({ "type": "ack", "seq": msg['seq'] })

                if msg:
                    seq_num = msg["seq"]
                    data = msg["data"]
                    if (seq_num not in self.recievedSequenceNums and data not in self.recievedData):
                        self.recievedSequenceNums.append(msg['seq'])
                        self.recievedData.append(data)
                        self.lastSeqNum = msg['seq']

                        if seq_num == self.next_expected_seq:
                        # Print out the data to stdout only if not duplicate
                            print(data, end='', flush=True)
                            self.next_expected_seq += 1

                            while self.next_expected_seq in self.buffer:
                                print(self.buffer[self.next_expected_seq], end='', flush=True)
                                del self.buffer[self.next_expected_seq]
                                self.next_expected_seq += 1
                        elif seq_num not in self.buffer:
                        # Buffer the out-of-order packet
                            self.buffer[seq_num] = data

                        # Always send back an ack
                        self.send({ "type": "ack", "seq": seq_num })
        return

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='receive data')
    args = parser.parse_args()
    sender = Receiver()
    sender.run()
